### ISSUE TITLE
Enable use of screenshot and video functionality when running tests

### ISSUE THREAD

**Issue by Benjen** [ironstar-io/testcafe-drupal#9]
Currently there is a bootstrap.js file which defines a test runner used when running tests within the Tokaido environment.

It would be good if we could utilise the same test runner process on non-tokaido projects.

Solution:
* Create a TestRunner class which can be configured to run tests using different browsers and test sources.

**Comment by Benjen** [comment]
@yjimk I have had a go at creating a [TestRunner](https://github.com/ironstar-io/testcafe-drupal/blob/issue/9-enable_use_of_screenshots/src/testRunner.js) class. However, when i try to use it [here](https://github.com/ironstar-io/testcafe-drupal/blob/issue/9-enable_use_of_screenshots/example/tests/bootstrap.js), it complains that TestRunner is not a constructor. 

I am thinking that the TestRunner class is not being exported correctly. Any ideas why?

```
/Volumes/workspace/dev/testcafe/testcafe-drupal-example-dev/workspace/tests/bootstrap.js:6
const testRunner = new TestRunner(
                   ^

TypeError: TestRunner is not a constructor
    at Object.<anonymous> (/Volumes/workspace/dev/testcafe/testcafe-drupal-example-dev/workspace/tests/bootstrap.js:6:20)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

**Comment by yjimk** [comment]
OK, I've done some digging on this one. It looks like the work you've done is actually all fine and might just be a problem with yarn workspaces!

When I first started having a look at this and getting the environment up and going again, it seems like workspaces was pulling the released version of testcafe-drupal, instead of the local version being used for development. So when I logged out `TestRunner`, it was coming back as `undefined`, which is of course not a constructor, but man, they really picked a bad error message for that case. 

So was reproducing your error at this point.

Making changes to the lib local then trying to log them out yielded no change either. It must be just how workspaces resolves dependencies, but seems that the order of preference is:

remote npm > local workspace

To fix this, I changed the `version` field in the `testcafe-drupal` library to something unreleased, in this case `0.0.12`, then the `devDependency` version for the example to `^0.0.12`. Re-ran `yarn` in the workspace root and was picking up the local version again. After that the tests were running without a hitch.

```
yarn run v1.17.3
$ node ./tests/bootstrap.js
here {
  Field: [Function: Field],
  Message: [Function: Message],
  Node: [Function: Node],
  config: {
    baseUrl: 'http://localhost:8080',
    node: { create: [Object] },
    users: { admin: [Object], editor: [Object], authenticated_user: [Object] },
    user: { login: [Object], add: [Object] },
    message: { selectors: [Object] }
  },
  baseUrl: 'http://localhost:8080',
  getConfig: [Function: getConfig],
  getSafe: [Function: getSafe],
  authenticatedUser: [
    'http://localhost:8080/user/login',
    [AsyncFunction],
    { preserveUrl: true }
  ],
  administratorUser: [
    'http://localhost:8080/user/login',
    [AsyncFunction],
    { preserveUrl: true }
  ],
  editorUser: [
    'http://localhost:8080/user/login',
    [AsyncFunction],
    { preserveUrl: true }
  ],
  TestRunner: [Function: TestRunner],
}
```

**Comment by yjimk** [comment]
Let me know if this fixes the issue for you, and then we can close this one :D

**Comment by Benjen** [comment]
Thanks @yjimk this resolves the issue
